BD-6 | Implement JWT custom authentication system in Skeleton
readytowork-org/go-gin-boilerplate pull request #23
Opened 2023-01-30 10:02 UTC by smooth-55

[Task Link](https://readytowork.atlassian.net/browse/BD-6)

To obtain JWT token : {{base_url}}/login
To refresh token : {{base_url}}/login/refresh

**What I did:**
- Created middleware to authenticate users using jwt-go
- Added refresh token and access token
- Added password field in the user model,
- Added unique constraints for email and phone
- used beforeCreate hook to encrypt plain text password as  hash form
- ask for confirm password while creating a user and validate it with saved hash password
- used dtos for request body data

2023-01-30 10:13 UTC, neekesh requested changes

2023-01-30 10:28 UTC, neekesh requested changes
please define struct in models
don't use single letter for variable declaration and defining parameters in funciton use a definite one

2023-02-14 04:22 UTC, neekesh approved these changes
LGTM

2023-02-14 05:23 UTC, Aavash approved these changes

2023-02-14 05:27 UTC, bhattaraibishal50 approved these changes

2023-02-14 05:46 UTC, sumitsapkota75 reviewed
Please remove password field for users on get all users API response.
And would be better to change obtain-jwt-token/  to login/

2023-02-14 06:08 UTC, sumitsapkota75 approved these changes

2023-02-14 06:08 UTC, merged