New arch
readytowork-org/go-gin-boilerplate pull request #42
Opened 2024-04-10 04:22 UTC by sawal-timsina

2024-05-02 04:23 UTC, Simant-Thapa-Magar reviewed
1. Image is not being built as go version seems different on different files. Error message says version 1.23 is required
2. Commands seem to be executing based on old structure. For eg:
- make create is creating migration files based on old structure
- make crud is throwing error of file not found
Please make sure each commands used are functioning as per changed structure

2024-05-02 04:27 UTC, sawal-timsina commented
> 1. Image is not being built as go version seems different on different files. Error message says version 1.23 is required
> 2. Commands seem to be executing based on old structure. For eg:
> 
> * make create is creating migration files based on old structure
> * make crud is throwing error of file not found
>   Please make sure each commands used are functioning as per changed structure

@Simant-Thapa-Magar  Thank you for taking your time to review this. I am quite busy in GS, would you mind taking a look at it if you are free?

2024-05-02 04:30 UTC, Simant-Thapa-Magar commented
> > 1. Image is not being built as go version seems different on different files. Error message says version 1.23 is required
> > 2. Commands seem to be executing based on old structure. For eg:
> > 
> > 
> > * make create is creating migration files based on old structure
> > * make crud is throwing error of file not found
> >   Please make sure each commands used are functioning as per changed structure
> 
> @Simant-Thapa-Magar Thank you for taking your time to review this. I am quite busy in GS, would you mind taking a look at it if you are free?

Apologies, I am busy as well with easyy-kids & easyy-adults. Please take your time as per convenience 🙇

2024-05-10 10:52 UTC, sawal-timsina commented
@smooth-55 thank you for the changes

2024-05-13 10:46 UTC, smooth-55 requested changes, later dismissed

2024-05-13 10:46 UTC, smooth-55 commented on services/stripe_test.go
> +		config.GetLogger(env),
config.GetLogger expects no arguments. Getting err `too many arguments in call to config.GetLogger
	have ("boilerplate-api/internal/config".Env)
	want ()`

2024-05-13 10:46 UTC, smooth-55 commented on services/stripe_test.go
> +		config.GetLogger(env),
Here too

2024-05-13 10:46 UTC, smooth-55 commented on services/stripe_test.go
> +		config.GetLogger(env),
Here too

2024-05-13 10:46 UTC, smooth-55 commented on services/stripe_test.go
> +		config.GetLogger(env),
Here too

2024-05-13 10:46 UTC, smooth-55 commented on tests/controllers_i_test/controllers_test.go
> +	"boilerplate-api/api/services"
There's no such package `controllers, repository, services` to import.
getting err:
`could not import boilerplate-api/api/controllers (no required module provides package "boilerplate-api/api/controllers")`

2024-05-13 10:46 UTC, smooth-55 commented on tests/repository_test/repository_test.go
> +	"boilerplate-api/api/repository"
could not import boilerplate-api/api/repository (no required module provides package "boilerplate-api/api/repository")

2024-05-20 11:31 UTC, smooth-55 reviewed
@sawal-timsina I've created two entity `user` and `product` and when I tried to call `getAllProductsByUserId` service in `user` package's controller and `GetOneUser` service in product package's controller I am getting import cycle issue.
Reason behind this issue is, this architecture is using same package for controllers, service, repository and routes.
we'll need to create separate package for each entities controllers, services, repository and routes.
like, user_service, user_repository and user_routes.

<img width="707" alt="Screenshot 2024-05-20 at 5 15 30 PM" src="https://github.com/readytowork-org/go-gin-skeleton/assets/59413582/fcd5824c-e899-46e0-8855-3d5067cc03d8">


Also, api endpoint is grouped by version, like api/v1/user. As per my perspective we also need to separate entities based on version itself as below.

├── api
  └── v1
    └── user
    └── products
  └── v2
   └── user
   └── products

cc: @Simant-Thapa-Magar

2024-05-20 11:37 UTC, sawal-timsina commented
> @sawal-timsina I've created two entity `user` and `product` and when I tried to call `getAllProductsByUserId` service in `user` package's controller and `GetOneUser` service in product package's controller I am getting import cycle issue. Reason behind this issue is, this architecture is using same package for controllers, service, repository and routes. we'll need to create separate package for each entities controllers, services, repository and routes. like, user_service, user_repository and user_routes.
> 
> <img alt="Screenshot 2024-05-20 at 5 15 30 PM" width="707" src="https://private-user-images.githubusercontent.com/59413582/332050828-fcd5824c-e899-46e0-8855-3d5067cc03d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDUwNjMsIm5iZiI6MTcxNjIwNDc2MywicGF0aCI6Ii81OTQxMzU4Mi8zMzIwNTA4MjgtZmNkNTgyNGMtZTg5OS00NmUwLTg4NTUtM2Q1MDY3Y2MwM2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDExMzI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MmMyNzFhMDJjODYxYzEwNmI2YWVjOGJjYjg3NGQwNGYwYWRkY2ZkMTAyZDgzMjczYzY2MTE0NWYxOGNmODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AjbUOLrlkahFooykGyLB53lTagrIl8apHTmYVRsRvHA">
> === Also, api endpoint is grouped by version, like api/v1/user. As per my perspective we also need to separate entities based on version itself as below.
> 
> <img alt="Screenshot 2024-05-20 at 5 17 25 PM" width="204" src="https://private-user-images.githubusercontent.com/59413582/332051334-9cbe0aa8-64bd-4772-87f8-99b8d970694f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDUwNjMsIm5iZiI6MTcxNjIwNDc2MywicGF0aCI6Ii81OTQxMzU4Mi8zMzIwNTEzMzQtOWNiZTBhYTgtNjRiZC00NzcyLTg3ZjgtOTliOGQ5NzA2OTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDExMzI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMTFmODYwYWNiNGRkZTkwMDkzNzEyZWFjODAzZDIxOWM0Yjc0NjRmNzdmOWQ0YjM0Zjc3NjIyNWRmNTE0YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o0dEyegoKrAs4Xgf824FD6w9wYSy2EBs1tE--EQiPaY">
> cc: @Simant-Thapa-Magar

@smooth-55 What do you suggest? How should we fix this?

2024-05-20 11:42 UTC, smooth-55 commented
> > @sawal-timsina I've created two entity `user` and `product` and when I tried to call `getAllProductsByUserId` service in `user` package's controller and `GetOneUser` service in product package's controller I am getting import cycle issue. Reason behind this issue is, this architecture is using same package for controllers, service, repository and routes. we'll need to create separate package for each entities controllers, services, repository and routes. like, user_service, user_repository and user_routes.
> > <img alt="Screenshot 2024-05-20 at 5 15 30 PM" width="707" src="https://private-user-images.githubusercontent.com/59413582/332050828-fcd5824c-e899-46e0-8855-3d5067cc03d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDUwNjMsIm5iZiI6MTcxNjIwNDc2MywicGF0aCI6Ii81OTQxMzU4Mi8zMzIwNTA4MjgtZmNkNTgyNGMtZTg5OS00NmUwLTg4NTUtM2Q1MDY3Y2MwM2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDExMzI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MmMyNzFhMDJjODYxYzEwNmI2YWVjOGJjYjg3NGQwNGYwYWRkY2ZkMTAyZDgzMjczYzY2MTE0NWYxOGNmODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AjbUOLrlkahFooykGyLB53lTagrIl8apHTmYVRsRvHA">
> > === Also, api endpoint is grouped by version, like api/v1/user. As per my perspective we also need to separate entities based on version itself as below.
> > <img alt="Screenshot 2024-05-20 at 5 17 25 PM" width="204" src="https://private-user-images.githubusercontent.com/59413582/332051334-9cbe0aa8-64bd-4772-87f8-99b8d970694f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDUwNjMsIm5iZiI6MTcxNjIwNDc2MywicGF0aCI6Ii81OTQxMzU4Mi8zMzIwNTEzMzQtOWNiZTBhYTgtNjRiZC00NzcyLTg3ZjgtOTliOGQ5NzA2OTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDExMzI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMTFmODYwYWNiNGRkZTkwMDkzNzEyZWFjODAzZDIxOWM0Yjc0NjRmNzdmOWQ0YjM0Zjc3NjIyNWRmNTE0YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o0dEyegoKrAs4Xgf824FD6w9wYSy2EBs1tE--EQiPaY">
> > cc: @Simant-Thapa-Magar
> 
> @smooth-55 What do you suggest? How should we fix this?

we'll need to create separate package for each entities controllers, services, repository and routes. like, user_service, user_repository and user_routes.

or we can do same as [THIS REPO](https://github.com/readytowork-org/go-gin-skeleton-app-based)

2024-07-02 08:46 UTC, merged